In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
def load_data(**kwargs):
    data_path = "../data/Titanic-Dataset.csv"
    df_train = pd.read_csv(data_path)
    return df_train

In [3]:
df = load_data()
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
def preprocess_dataset(df):

    titles_dict = {'Capt': 'Other',
               'Major': 'Other',
               'Jonkheer': 'Other',
               'Don': 'Other',
               'Sir': 'Other',
               'Dr': 'Other',
               'Rev': 'Other',
               'Countess': 'Other',
               'Dona': 'Other',
               'Mme': 'Mrs',
               'Mlle': 'Miss',
               'Ms': 'Miss',
               'Mr': 'Mr',
               'Mrs': 'Mrs',
               'Miss': 'Miss',
               'Master': 'Master',
               'Lady': 'Other'}

    df['Title'] = df.Name.str.extract('([A-Za-z]+)\.', expand=False)
    df['Title'] = df['Title'].map(titles_dict)
    df.Title.fillna('Mr', inplace=True)

    means = df.groupby('Title')['Age'].mean().to_dict()

    df.loc[df.Age.isna(),'Age'] = df['Title'].loc[df.Age.isna()].map(means)

    df.Embarked = df.Embarked.fillna('S')

    df["HasCabin"] = df["Cabin"].notna().astype(int)
    
    df['FamilySize'] = df['SibSp'] + df['Parch']
    df.drop('SibSp',axis=1,inplace=True)
    df.drop('Parch',axis=1,inplace=True)

    return df

In [5]:
df2 = preprocess_dataset(df)

/tmp/ipykernel_14594/303533080.py:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Title.fillna('Mr', inplace=True)

In [6]:
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked,Title,HasCabin,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,A/5 21171,7.2500,NaN,S,Mr,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,PC 17599,71.2833,C85,C,Mrs,1,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,STON/O2. 3101282,7.9250,NaN,S,Miss,0,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,113803,53.1000,C123,S,Mrs,1,1
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,373450,8.0500,NaN,S,Mr,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,211536,13.0000,NaN,S,Other,0,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,112053,30.0000,B42,S,Miss,1,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21.845638,W./C. 6607,23.4500,NaN,S,Miss,0,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,111369,30.0000,C148,C,Mr,1,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,370376,7.7500,NaN,Q,Mr,0,0