# Optimización de Hiperparámetros con Keras Tuner – Hyperband

[paper link](https://arxiv.org/pdf/1603.06560)


## 1. Importaciones y configuración

In [1]:

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import keras_tuner as kt
import numpy as np
import pandas as pd

print("TensorFlow version:", tf.__version__)
print("GPUs disponibles:", tf.config.list_physical_devices('GPU'))

TensorFlow version: 2.19.0
GPUs disponibles: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


## 2. Carga del dataset

In [2]:

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

x_train = np.expand_dims(x_train, -1)
x_test = np.expand_dims(x_test, -1)

print("Shape train:", x_train.shape)

Shape train: (60000, 28, 28, 1)


## 3. Definición del espacio de búsqueda

In [3]:

def build_model(hp1):
    model = keras.Sequential()
    model.add(layers.Input(shape=(28, 28, 1)))

    # Número de filtros
    filters = hp1.Choice("filters", [16, 32, 64])
    model.add(layers.Conv2D(filters, 3, activation="relu"))
    model.add(layers.MaxPooling2D())

    # Dropout
    dropout = hp1.Float("dropout", 0.0, 0.5, step=0.25)
    model.add(layers.Dropout(dropout))

    model.add(layers.Flatten())

    # Unidades densas
    units1 = hp1.Int("units1", 64, 256, step=64)
    model.add(layers.Dense(units1, activation="relu"))

    #model.add(layers.Dense(int(units1/2), activation="relu"))
    #model.add(layers.Dense(int(units1/4), activation="relu"))

    model.add(layers.Dense(10, activation="softmax"))

    # Learning rate
    lr = hp1.Float("lr", 1e-4, 1e-2, sampling="log")

    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=lr),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model


## 4. Configuración de Hyperband

In [6]:

# tuner = kt.Hyperband(
#     build_model,
#     objective="val_accuracy",
#     max_epochs=20,
#     factor=3,
#     directory="hyperband_demo",
#     project_name="mnist"
# )

tuner = kt.BayesianOptimization(
    build_model,
    objective="val_accuracy",
    num_initial_points = 20,
    directory="hyperband_demo",
    project_name="mnist"
)


## 5. Ejecución de la búsqueda

In [7]:
tuner.search(
    x_train, y_train,
    validation_split=0.2,
    epochs=20,
    batch_size=128,
    verbose=1
)

Trial 10 Complete [00h 00m 28s]
val_accuracy: 0.987666666507721

Best val_accuracy So Far: 0.9884166717529297
Total elapsed time: 00h 04m 57s


## 6. Mejores hiperparámetros encontrados

In [8]:
best_hp = tuner.get_best_hyperparameters(1)[0]

for k in best_hp.values:
    print(f"{k}: {best_hp.get(k)}")

filters: 16
dropout: 0.5
units1: 128
lr: 0.007776427195474676


## 7. Comparativa entre configuraciones
Vamos a comparar **las mejores 5 configuraciones** para justificar
por qué la ganadora es realmente superior.

In [9]:
results = []

for trial in tuner.oracle.trials.values():
    results.append({
        "trial_id": trial.trial_id,
        "val_accuracy": trial.metrics.get_best_value("val_accuracy"),
        **trial.hyperparameters.values
    })

df = pd.DataFrame(results).sort_values("val_accuracy", ascending=False)
df.head()

  trial_id  val_accuracy  filters  dropout  units1        lr
1       01      0.988417       16     0.50     128  0.007776
7       07      0.987833       16     0.25     256  0.004081
9       09      0.987667       64     0.50     256  0.007014
2       02      0.987250       16     0.25      64  0.000509
6       06      0.986833       16     0.25      64  0.006827

In [10]:
df.tail()

  trial_id  val_accuracy  filters  dropout  units1        lr
5       05      0.986083       16      0.0     128  0.000508
8       08      0.986083       64      0.5     192  0.000138
4       04      0.985667       64      0.0     128  0.005860
0       00      0.985250       16      0.0     192  0.006429
3       03      0.984167       32      0.5     192  0.000126

In [11]:
best_models = tuner.get_best_models(num_models=1)
best_model = best_models[0]

/home/gibran/anaconda3/envs/tf219/lib/python3.10/site-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 14 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [12]:
best_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 26, 26, 16)     │           160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 13, 13, 16)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 13, 13, 16)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 2704)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │       346,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 347,690 (1.33 MB)

 Trainable params: 347,690 (1.33 MB)

 Non-trainable params: 0 (0.00 B)